#!/bin/bash

./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa9 contenedores9 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa10 contenedores10 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa11 contenedores11 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa14 contenedores14 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa13 contenedores13 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa15 contenedores15 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa16 contenedores16 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa17 contenedores17 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores18 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa9 contenedores9 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa10 contenedores10 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa11 contenedores11 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa14 contenedores14 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa13 contenedores13 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa15 contenedores15 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa16 contenedores16 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa17 contenedores17 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores18 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa19 contenedores19 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa9 contenedores9 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa10 contenedores10 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa11 contenedores11 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa14 contenedores14 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa13 contenedores13 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa15 contenedores15 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa16 contenedores16 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa17 contenedores17 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores18 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores19 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores20 heuristica3
./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa13 contenedores13 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa14 contenedores14 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa15 contenedores15 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa16 contenedores16 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa17 contenedores17 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa18 contenedores18 heuristica0
