#!/bin/bash

./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa9 contenedores9 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa10 contenedores10 heuristica1
./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa9 contenedores9 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa10 contenedores10 heuristica2
./ASTARStowage.sh  ./ASTAR-tests mapa1 contenedores1 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa2 contenedores2 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa3 contenedores3 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa4 contenedores4 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa5 contenedores5 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa6 contenedores6 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa7 contenedores7 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa8 contenedores8 heuristica0
./ASTARStowage.sh  ./ASTAR-tests mapa12 contenedores12 heuristica0
